### ISSUE TITLE
The package does not see files like "en.json"

### ISSUE THREAD

**Issue by nafanyka** [MohmmedAshraf/laravel-translations#26]
When importing translation files, the package does not add translations that are located at the root of the translations folder. For example, lang/en.json

**Comment by rabol** [comment]
Same issue here

**Comment by MohmmedAshraf** [comment]
Hi @nafanyka I've tried this multiple times and it working correctly, Please inform me if you are still experiencing any issues.

**Comment by flarpy** [comment]
![lang](https://github.com/MohmmedAshraf/laravel-translations/assets/2345922/c0ad71bc-ce68-4185-8620-a3c0ae6870c7)
![image](https://github.com/MohmmedAshraf/laravel-translations/assets/2345922/9941e696-96ea-457c-9e81-37bc597c5eb3)

Very happy to find this package as I was just about to write something very similar. Looks good so far but I think I'm misunderstanding how to import files. If I import from this structure es.json and fr.json are not parsed or saved in the db. Is this expected behaviour?
